### ISSUE TITLE
Frequency LFO input

### ISSUE THREAD

**Issue by craigyjp** [polykit/pico-dco#1]
It's really neat and I'm building one for a test, but a DCO needs modulation. How do you modulate the frequency from an LFO?

**Comment by polykit** [comment]
@craigyjp This is currently not implemented. DCO frequency is controlled by the microcontroller so you can implement it in software. You could use one of the ADC inputs for external control or CV input.

**Comment by craigyjp** [comment]
I wouldn't know how to do that, but it's an integral function of a DCOs or VCO to be modulated.

**Comment by polykit** [comment]
You are welcome to implement it then.

**Comment by craigyjp** [comment]
I have found some one that has implemented FM linear input on ADC0, just need to compile and test it
